- name: Check if original .zshrc is present
  stat: path=~/.zshrc
  register: file

- name: Backup original .zshrc
  copy: src=~/.zshrc dest=.zshrc_backup
  when: file.stat.exists

- name: Copy new .zshrc
  copy: src="{{ role_path }}/files/.zshrc" dest=~/.zshrc

- name: Make sure that .zshrc.local is present
  file: path=~/.zshrc.local state=touch

- name: Check if original .zsh/ is present
  stat: path=~/.zsh
  register: directory

- name: Backup original .zsh/
  command: cp -r ~/.zsh ~/.zsh_backup
  when: directory.stat.isdir is defined and directory.stat.isdir

- name: Delete original .zsh/
  file: path=~/.zsh state=absent

- name: Copy new .zsh/
  copy: src="{{ role_path }}/files/.zsh" dest=~ directory_mode=yes

